colours:
  blue:
    min_hsv: [80,85,110]
    max_hsv: [112,220,255]
    inv_hsv: False
  yellow:
    min_hsv: [0,0,0]
    max_hsv: [179,255,250]
    inv_hsv: True
  red:
    min_hsv: [0,117,33]
    max_hsv: [16,255,255]
    inv_hsv: False
  green:
    min_hsv: [20,0,188]
    max_hsv: [109,241,255]
    inv_hsv: False
  black:
    min_hsv: [0,0,66]
    max_hsv: [123,255,126]
    inv_hsv: False
physical_thresholds:
  robot_area:     !!python/tuple [220.0, 810.0]
  black_dot_area: !!python/tuple [20.0, 76.0]
  black_dot_dist: !!python/tuple [16.0, 28.0]
  ball_radius:    !!python/tuple [0.0, 15.0]
  ball_area:      !!python/tuple [40.0, 140.0]
  plate_area:     !!python/tuple [400.0, 2800.0]
  blob_area:     !!python/tuple [220.0, 4050.0]
  pnp_dist:       0.91
  max_foreground_obj: 3
  cc_area:        15
  offsets:        !!python/tuple [20,20,20,20]

