colours:
  black:
    inv_hsv: false
    max_hsv: [123.0, 255.0, 126.0]
    min_hsv: [0.0, 0.0, 66.0]
  blue:
    inv_hsv: false
    max_hsv: [112.0, 220.0, 255.0]
    min_hsv: [80.0, 85.0, 110.0]
  green:
    inv_hsv: false
    max_hsv: [93.0, 241.0, 255.0]
    min_hsv: [20.0, 0.0, 194.0]
  red:
    inv_hsv: false
    max_hsv: [12.0, 255.0, 255.0]
    min_hsv: [0.0, 117.0, 33.0]
  yellow:
    inv_hsv: true
    max_hsv: [175.0, 255.0, 251.0]
    min_hsv: [0.0, 0.0, 0.0]
physical_thresholds:
  ball_area: !!python/tuple [40.0, 140.0]
  ball_radius: !!python/tuple [0.0, 15.0]
  black_dot_area: !!python/tuple [20.0, 76.0]
  black_dot_dist: !!python/tuple [16.0, 28.0]
  blob_area: !!python/tuple [220.0, 4050.0]
  cc_area: 15
  plate_area: !!python/tuple [400.0, 2800.0]
  pnp_dist: !!python/tuple [0.92000000000000004, 0.90000000000000002]
  robot_area: !!python/tuple [220.0, 810.0]
