colours:
  black:
    inv_hsv: false
    max_hsv: [122.0, 255.0, 126.0]
    min_hsv: [0.0, 0.0, 66.0]
  blue:
    inv_hsv: false
    max_hsv: [255.0, 255.0, 255.0]
    min_hsv: [0.0, 69.0, 80.0]
  green:
    inv_hsv: false
    max_hsv: [112.0, 255.0, 255.0]
    min_hsv: [17.0, 53.0, 183.0]
  red:
    inv_hsv: false
    max_hsv: [12.0, 255.0, 255.0]
    min_hsv: [0.0, 110.0, 40.0]
  yellow:
    inv_hsv: true
    max_hsv: [179.0, 255.0, 247.0]
    min_hsv: [0.0, 0.0, 0.0]
physical_thresholds:
  ball_area: !!python/tuple [40.0, 150.0]
  ball_radius: !!python/tuple [4.0, 15.0]
  black_dot_area: !!python/tuple [20.0, 80.0]
  black_dot_dist: !!python/tuple [16.0, 35.0]
  robot_area: !!python/tuple [180.0, 810.0]
